version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - jenkins

volumes:
  jenkins_home: